### ISSUE TITLE
`obe.__init__()` has misspelled positional argument

### ISSUE THREAD

**Issue by bdalfavero** [JQIamo/pylcp#65] opened 2022-09-27 19:08 UTC
On line 144 of `obe.__init__()` you can see that the positional argument for the Hamiltonian is spelled `hamitlonian` (with the t and l swapped) instead of `hamiltonian`, yet in the function body it is referenced as `hamiltonian`. The `obe` object cannot be initialized. I believe the same goes for `rateeq`. All of my attempts to initialize these objects have failed.

**Comment by dsbarker** [comment] 2022-09-28 01:23
Can you provide a minimum working example that produces the error with the full trace back? I've run code both with and without the misspelling and the `obe` object initialized without an error. The `hamitlonian` argument is positional and stored as `hamiltonian` inside the call to `super.__init__`, so the mispelling should not cause `obe.__init__` to fail.

This is a duplicate of #64, so it's already fixed in the development branch. The fix will be available on PyPi when we create the next bugfix version.

**Comment by bdalfavero** [comment] 2022-09-28 20:07
I was not able to reproduce the error. Sorry to bother you.

**Comment by dsbarker** [comment] 2022-10-11 12:55
I'm glad that you got the code working. Please reach out here or on the google group if you have any additional issues.

**Closed as completed by dsbarker** 2022-10-11 12:55 UTC
Labels: bug
